# Generated by Django 3.0 on 2019-12-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='share_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='post.Post', verbose_name='Share Post'),
        ),
    ]
